settings = {
    'GAMMA': 0.99,
    'EPSILON_0': 0.5,
    'EPSILON_DISCOUNT_COEF': 0.999,
    'EPSILON_MIN_VALUE': 0.0,

    'EXP_REPLAY_BUFFER_SIZE': int(1e7),

    'REWARD_WAIT_TIME': 0.04,  # secondi

    'LEARNING_BATCH_SIZE': 64,
    'LEARNING_STEP_NUMBER': 4,
    'TARGET_Q_FUNCTION_UPDATE_STEP_NUMBER': 2000,

    'ADAM_LEARNING_RATE': 1e-2,

    'ROOM_PASSWORD': 'brumbrum',

    'VISUALIZE': 1,
}
