settings = {
    'GAMMA': 0.99,
    'EPSILON_0': 0.5,
    'EPSILON_DISCOUNT_COEF': 0.999,
    'EPSILON_MIN_VALUE': 0.1,

    'EXP_REPLAY_BUFFER_SIZE': int(1e6),

    'REWARD_WAIT_TIME': 0.04,  # secondi

    'LEARNING_BATCH_SIZE': 32,
    'LEARNING_STEP_NUMBER': 2,
    'TARGET_Q_FUNCTION_UPDATE_STEP_NUMBER': 1000,

    'ADAM_LEARNING_RATE': 1e-2,

    'ROOM_PASSWORD': 'hellokitty',
}
